import { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

const translations = {
  english: {
    welcome: 'Welcome to Madurai One',
    subtitle: 'Your travel companion in Madurai',
    enterPhone: 'Enter your mobile number',
    phonePlaceholder: 'Mobile Number',
    getOTP: 'Get OTP',
    resendOTP: 'Resend OTP in',
    seconds: 'seconds',
    enterOTP: 'Enter the OTP',
    otpSent: 'OTP sent to',
    verify: 'Verify',
    invalidOTP: 'Invalid OTP. Please try again.',
    selectLanguage: 'Select your preferred language',
    tamil: 'Tamil',
    tamilDesc: 'தமிழ்',
    englishLang: 'English',
    englishDesc: 'English',
    blindMode: 'Blind / Accessibility Mode',
    blindModeDesc: 'Larger text, voice instructions',
    continue: 'Continue',
    enableLocation: 'Enable Location',
    locationDesc: 'We need your location to show nearby transport options',
    useCurrentLocation: 'Use Current Location',
    enterManually: 'Enter Manually',
    locationSet: 'Location set successfully',
    selectTransport: 'Select your transport',
    governmentBus: 'Government Bus',
    privateBus: 'Private Bus',
    auto: 'Auto',
    car: 'Car',
    bike: 'Bike',
    train: 'Train',
    busNumber: 'Bus Number',
    busNumberPlaceholder: 'e.g., TN 45 A 1234',
    route: 'Select Route',
    calculateFare: 'Calculate Fare',
    fare: 'Fare',
    proceedToPay: 'Proceed to Pay',
    paymentMethods: 'Select Payment Method',
    upi: 'UPI',
    card: 'Card',
    netBanking: 'Net Banking',
    payNow: 'Pay Now',
    processing: 'Processing...',
    paymentSuccess: 'Payment Successful!',
    ticketGenerated: 'Your ticket has been generated',
    viewTicket: 'View Ticket',
    ticket: 'Ticket',
    validUntil: 'Valid until',
    downloadTicket: 'Download Ticket',
    shareTicket: 'Share Ticket',
    bookNow: 'Book Now',
    openWebsite: 'Open Website',
    maduraiTravels: 'Madurai Travels',
    eglooTravels: 'eGloo Travels',
    griffinTravels: 'Griffin Travels',
    sairoadTravels: 'Sai Road Travels',
    radhaTravels: 'Radha Travels',
    vagaimetraAuto: 'Vagai Metra Auto',
    vaigaiMetraAuto: 'Vaigai Metra Auto',
    gozoCabs: 'Gozo Cabs',
    fastTrackTaxi: 'Fast Track Taxi',
    bharatTaxi: 'Bharat Taxi',
    savaari: 'Savaari',
    threeBestRated: 'Three Best Rated',
    srtCarRentals: 'SRT Car Rentals',
    rapido: 'Rapido',
    irctc: 'IRCTC',
    bookTrain: 'Book Train Ticket',
    bookCab: 'Book Cab',
    bookBike: 'Book Bike',
    bookAuto: 'Book Auto',
    back: 'Back',
    logout: 'Logout',
    payment: 'Payment',
    selectService: 'Select Service',
    sendMoney: 'Send Money',
    sendMoneyDesc: 'Transfer money to any UPI ID or bank account',
    bookTicket: 'Book Ticket',
    bookTicketDesc: 'Book bus, train, or auto tickets',
    quickActions: 'Quick Actions',
    busTicket: 'Bus Ticket',
    trainTicket: 'Train Ticket',
    autoBooking: 'Auto Booking',
    recipientUPI: 'Recipient UPI / Phone',
    recipientPlaceholder: 'Enter UPI ID or phone number',
    amount: 'Amount',
    quickAmount: 'Quick Amount',
    ticketType: 'Ticket Type',
    paymentSuccess: 'Payment Successful!',
    transactionComplete: 'Your transaction is complete',
    transactionId: 'Transaction ID',
    type: 'Type',
    paidVia: 'Paid Via',
    downloadReceipt: 'Download Receipt',
    newPayment: 'New Payment',
    goHome: 'Go Home',
    enterValidAmount: 'Please enter a valid amount',
    enterRecipient: 'Please enter recipient details',
    selectPaymentMethod: 'Please select a payment method',
    paymentFailed: 'Payment failed. Please try again.',
    autoServices: 'Auto Services',
    website: 'Website',
    app: 'App',
    quickBooking: 'Quick Booking',
    quickBookingDesc: 'Book tickets or send money instantly',
    selectRoute: 'Select Route',
    proceedToPayment: 'Proceed to Payment',
    scanToPay: 'Scan to Pay',
    scanQRCode: 'Scan the QR code with any UPI app',
    payToUPI: 'Pay to: maduraione@upi',
    openApp: 'Open Payment App',
    makePaymentNote: 'After making payment, click "I Have Paid" below',
    verifyPayment: 'Verify Payment',
    confirmingPayment: 'Confirming payment...',
    confirmPayment: 'I Have Paid',
    verifying: 'Verifying...',
    ticketId: 'Ticket ID',
    razorpayPayment: 'Razorpay Secure Payment',
    securePayment: 'Pay securely with Razorpay',
    paymentId: 'Payment ID'
  },
  tamil: {
    welcome: 'மதுரை ஒன் வரவேற்கிறது',
    subtitle: 'மதுரையில் உங்கள் பயண துணை',
    enterPhone: 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
    phonePlaceholder: 'மொபைல் எண்',
    getOTP: 'OTP பெறுக',
    resendOTP: 'OTP மீண்டும் அனுப்பு',
    seconds: 'விநாடிகளில்',
    enterOTP: 'OTP ஐ உள்ளிடவும்',
    otpSent: 'OTP அனுப்பப்பட்ட எண்',
    verify: 'சரிபார்க்க',
    invalidOTP: 'தவறான OTP. மீண்டும் முயற்சிக்கவும்.',
    selectLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    tamil: 'தமிழ்',
    tamilDesc: 'தமிழ்',
    englishLang: 'ஆங்கிலம்',
    englishDesc: 'English',
    blindMode: 'குருட்டு / அணுகல் முறை',
    blindModeDesc: 'பெரிய எழுத்துக்கள், குரல் வழிமுறைகள்',
    continue: 'தொடர்க',
    enableLocation: 'இருப்பிடத்தை இயக்கு',
    locationDesc: 'அருகிலுள்ள போக்குவரத்து விருப்பங்களைக் காட்ட உங்கள் இருப்பிடம் தேவை',
    useCurrentLocation: 'தற்போதைய இருப்பிடத்தைப் பயன்படுத்து',
    enterManually: 'கைமுறையாக உள்ளிடு',
    locationSet: 'இருப்பிடம் வெற்றிகரமாக அமைக்கப்பட்டது',
    selectTransport: 'போக்குவரத்தைத் தேர்ந்தெடுக்கவும்',
    governmentBus: 'அரசு பேருந்து',
    privateBus: 'தனியார் பேருந்து',
    auto: 'ஆட்டோ',
    car: 'கார்',
    bike: 'மோட்டார்',
    train: 'ரயில்',
    busNumber: 'பேருந்து எண்',
    busNumberPlaceholder: 'உதா., TN 45 A 1234',
    route: 'பாதையைத் தேர்ந்தெடுக்கவும்',
    calculateFare: 'கட்டணத்தைக் கணக்கிடு',
    fare: 'கட்டணம்',
    proceedToPay: 'பணம் செலுத்து',
    paymentMethods: 'பணம் செலுத்தும் முறையைத் தேர்ந்தெடுக்கவும்',
    upi: 'UPI',
    card: 'கார்டு',
    netBanking: 'நெட் வங்கி',
    payNow: 'இப்போது பணம் செலுத்து',
    processing: 'செயலாக்கம்...',
    paymentSuccess: 'பணம் செலுத்தல் வெற்றி!',
    ticketGenerated: 'உங்கள் டிக்கெட் உருவாக்கப்பட்டது',
    viewTicket: 'டிக்கெட்டைப் பார்க்க',
    ticket: 'டிக்கெட்',
    validUntil: 'செல்லுபடியாகும் வரை',
    downloadTicket: 'டிக்கெட்டைப் பதிவிறக்கு',
    shareTicket: 'டிக்கெட்டைப் பகிர்',
    bookNow: 'இப்போது முன்பதிவு செய்க',
    openWebsite: 'வலைத்தளத்தைத் திற',
    maduraiTravels: 'மதுரை டிராவல்ஸ்',
    eglooTravels: 'இ-க்ளூ டிராவல்ஸ்',
    griffinTravels: 'கிரிஃபின் டிராவல்ஸ்',
    sairoadTravels: 'சாய் ரோட் டிராவல்ஸ்',
    radhaTravels: 'ராதா டிராவல்ஸ்',
    vagaimetraAuto: 'வாகை மேட்ரா ஆட்டோ',
    vaigaiMetraAuto: 'வைகை மேட்ரா ஆட்டோ',
    gozoCabs: 'கோசோ கேப்ஸ்',
    fastTrackTaxi: 'ஃபாஸ்ட் ட்ராக் டாக்ஸி',
    bharatTaxi: 'பாரத் டாக்ஸி',
    savaari: 'சவாரி',
    threeBestRated: 'த்ரீ பெஸ்ட் ரேட்டட்',
    srtCarRentals: 'எஸ்ஆர்டி கார் ரெண்டல்ஸ்',
    rapido: 'ரேபிடோ',
    irctc: 'ஐஆர்சிடிசி',
    bookTrain: 'ரயில் டிக்கெட் முன்பதிவு',
    bookCab: 'கேப் முன்பதிவு',
    bookBike: 'பைக் முன்பதிவு',
    bookAuto: 'ஆட்டோ முன்பதிவு',
    back: 'மீண்டும்',
    logout: 'வெளியேறு',
    payment: 'பணம் செலுத்தல்',
    selectService: 'சேவையைத் தேர்ந்தெடுக்கவும்',
    sendMoney: 'பணம் அனுப்பு',
    sendMoneyDesc: 'எந்த UPI ID அல்லது வங்கி கணக்கிற்கும் பணம் அனுப்பவும்',
    bookTicket: 'டிக்கெட் முன்பதிவு',
    bookTicketDesc: 'பேருந்து, ரயில் அல்லது ஆட்டோ டிக்கெட் முன்பதிவு செய்யவும்',
    quickActions: 'விரைவு செயல்கள்',
    busTicket: 'பேருந்து டிக்கெட்',
    trainTicket: 'ரயில் டிக்கெட்',
    autoBooking: 'ஆட்டோ முன்பதிவு',
    recipientUPI: 'பெறுநர் UPI / தொலைபேசி',
    recipientPlaceholder: 'UPI ID அல்லது தொலைபேசி எண்ணை உள்ளிடவும்',
    amount: 'தொகை',
    quickAmount: 'விரைவு தொகை',
    ticketType: 'டிக்கெட் வகை',
    paymentSuccess: 'பணம் செலுத்தல் வெற்றி!',
    transactionComplete: 'உங்கள் பரிவர்த்தனை முடிந்தது',
    transactionId: 'பரிவர்த்தனை ID',
    type: 'வகை',
    paidVia: 'செலுத்திய முறை',
    downloadReceipt: 'ரசீதைப் பதிவிறக்கு',
    newPayment: 'புதிய பணம் செலுத்தல்',
    goHome: 'முகப்பிற்குச் செல்லவும்',
    enterValidAmount: 'சரியான தொகையை உள்ளிடவும்',
    enterRecipient: 'பெறுநர் விவரங்களை உள்ளிடவும்',
    selectPaymentMethod: 'பணம் செலுத்தும் முறையைத் தேர்ந்தெடுக்கவும்',
    paymentFailed: 'பணம் செலுத்தல் தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    autoServices: 'ஆட்டோ சேவைகள்',
    website: 'வலைத்தளம்',
    app: 'ஆப்',
    quickBooking: 'விரைவு முன்பதிவு',
    quickBookingDesc: 'டிக்கெட் முன்பதிவு செய்யவும் அல்லது பணம் அனுப்பவும்',
    selectRoute: 'பாதையைத் தேர்ந்தெடுக்கவும்',
    proceedToPayment: 'பணம் செலுத்தச் செல்லவும்',
    scanToPay: 'பணம் செலுத்த ஸ்கேன் செய்யவும்',
    scanQRCode: 'எந்த UPI ஆப்லும் QR கோடை ஸ்கேன் செய்யவும்',
    payToUPI: 'பணம் செலுத்தவும்: maduraione@upi',
    openApp: 'பணம் செலுத்தும் ஆப் திறக்கவும்',
    makePaymentNote: 'பணம் செலுத்திய பிறகு, கீழே "நான் பணம் செலுத்தினேன்" என்பதைக் கிளிக் செய்யவும்',
    verifyPayment: 'பணம் சரிபார்க்கவும்',
    confirmingPayment: 'பணம் உறுதிசெய்யப்படுகிறது...',
    confirmPayment: 'நான் பணம் செலுத்தினேன்',
    verifying: 'சரிபார்க்கிறது...',
    ticketId: 'டிக்கெட் ID'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const { user, updateProfile } = useAuth();
  const [language, setLanguage] = useState(user?.language || 'english');
  const [blindMode, setBlindMode] = useState(user?.blindMode || false);

  useEffect(() => {
    if (user?.language) {
      setLanguage(user.language);
    }
    if (user?.blindMode !== undefined) {
      setBlindMode(user.blindMode);
    }
  }, [user]);

  const changeLanguage = async (lang) => {
    setLanguage(lang);
    if (user) {
      await updateProfile({ language: lang });
    }
  };

  const toggleBlindMode = async () => {
    const newValue = !blindMode;
    setBlindMode(newValue);
    if (user) {
      await updateProfile({ blindMode: newValue });
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.english[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, blindMode, changeLanguage, toggleBlindMode, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
